# Generated by Django 6.0.5 on 2026-05-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff')], default='TEACHING', max_length=20)),
                ('staff_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='staff_passports/')),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, related_name='assigned_staff', to='academics.schoolclass')),
                ('assigned_subjects', models.ManyToManyField(blank=True, related_name='assigned_staff', to='academics.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['school', 'staff_type'], name='staffs_staf_school__c806be_idx'), models.Index(fields=['school', 'status'], name='staffs_staf_school__86b13b_idx'), models.Index(fields=['staff_id'], name='staffs_staf_staff_i_993e7b_idx')],
            },
        ),
    ]
