# Generated by Django 6.0.5 on 2026-05-22 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0004_school_result_stamp'),
        ('students', '0002_studentprofile_result_qr_studentprofile_result_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('TRANSFER', 'Class Transfer'), ('REPEAT', 'Repeat Class')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_moved_from', to='academics.schoolclass')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_movements', to='schools.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_movements', to='students.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicterm')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_moved_to', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
