# Generated by Django 6.0.5 on 2026-05-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0002_studentprofile_result_qr_studentprofile_result_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('pass_mark', models.PositiveIntegerField(default=50)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_score_immediately', models.BooleanField(default=True)),
                ('allow_retake', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbt_exams', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='academics.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='academics.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='students.studentprofile')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cbt.cbtexam')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbt_questions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_questions', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_questions', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_questions', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='cbt.cbtquestion'),
        ),
        migrations.CreateModel(
            name='CBTAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('', 'Not Answered'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='cbt.cbtattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_question_records', to='cbt.cbtquestion')),
            ],
        ),
        migrations.AddField(
            model_name='cbtattempt',
            name='questions',
            field=models.ManyToManyField(related_name='attempts', through='cbt.CBTAttemptQuestion', to='cbt.cbtquestion'),
        ),
        migrations.AddIndex(
            model_name='cbtquestion',
            index=models.Index(fields=['school', 'school_class', 'subject'], name='cbt_cbtques_school__7aeac9_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtquestion',
            index=models.Index(fields=['difficulty'], name='cbt_cbtques_difficu_b7ba83_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtquestion',
            index=models.Index(fields=['is_active'], name='cbt_cbtques_is_acti_fd17ab_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtexam',
            index=models.Index(fields=['school', 'school_class', 'subject'], name='cbt_cbtexam_school__fbb3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtexam',
            index=models.Index(fields=['session', 'term'], name='cbt_cbtexam_session_106a30_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtexam',
            index=models.Index(fields=['is_active'], name='cbt_cbtexam_is_acti_1d2e58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cbtattemptquestion',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='cbtattempt',
            index=models.Index(fields=['school', 'exam'], name='cbt_cbtatte_school__fb8364_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtattempt',
            index=models.Index(fields=['student', 'exam'], name='cbt_cbtatte_student_1af920_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtattempt',
            index=models.Index(fields=['status'], name='cbt_cbtatte_status_967399_idx'),
        ),
    ]
