# Generated by Django 6.0.5 on 2026-05-10 20:59

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='diagram',
            field=models.ImageField(blank=True, help_text='Optional diagram, graph, equation image or science illustration.', null=True, upload_to='cbt_diagrams/'),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_a',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_b',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_c',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_d',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='question_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Supports maths, science symbols, diagrams, images, tables and formatted text.'),
        ),
    ]
