# Generated by Django 6.0.5 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_cbtquestion_diagram_alter_cbtquestion_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='estimated_time',
            field=models.PositiveIntegerField(default=60, help_text='Estimated seconds'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='is_calculation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/questions/'),
        ),
    ]
