# Generated by Django 6.0.5 on 2026-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('portal_subpath', models.SlugField(help_text='Public portal path, e.g. berachah-school', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], db_index=True, default='TRIAL', max_length=20)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('result_checker_enabled', models.BooleanField(default=True)),
                ('cbt_enabled', models.BooleanField(default=True)),
                ('finance_enabled', models.BooleanField(default=True)),
                ('parent_portal_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='schools_sch_slug_51c325_idx'), models.Index(fields=['portal_subpath'], name='schools_sch_portal__3fcfae_idx'), models.Index(fields=['subscription_status'], name='schools_sch_subscri_128454_idx'), models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx')],
            },
        ),
    ]
