# Generated by Django 6.0.5 on 2026-05-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_subscriptionplan_schoolsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accent_color',
            field=models.CharField(default='#22c55e', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_custom_branding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='Example: schoolname.com', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='maintenance_message',
            field=models.TextField(blank=True, default='This school portal is temporarily under maintenance.'),
        ),
        migrations.AddField(
            model_name='school',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.SlugField(blank=True, help_text='Example: brightstar', max_length=100),
        ),
    ]
