# Generated by Django 6.0.5 on 2026-05-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('LESSON_NOTE', 'Lesson Note'), ('ASSIGNMENT', 'Assignment'), ('PRESENTATION', 'Presentation'), ('VIDEO_LINK', 'Video Link'), ('OTHER', 'Other')], default='LESSON_NOTE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_resources/')),
                ('external_link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='academics.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='academics.academicterm')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lesson_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'school_class', 'subject'], name='lessons_les_school__6e883b_idx'), models.Index(fields=['session', 'term'], name='lessons_les_session_513345_idx'), models.Index(fields=['is_published'], name='lessons_les_is_publ_2b6cd4_idx')],
            },
        ),
    ]
